name: Deploy to REG.RU

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 37.140.192.191:22
          username: u1618701        
          password: ${{ secrets.23TmExo2wJnE4HCz }}
          server-dir: /www/yagoda-coffee58.ru/  
          protocol: ftps            
