name: Deploy to REG.RU

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 37.140.192.191
          username: u1618701 
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp       
          server-dir: /www/yagoda-coffee58.ru/ 
